### PR TITLE
Replace == 'Kerbin' with isHomeWorld

### PR DESCRIPTION
**Pull request by NathanKell**
Thanks to Blacks for this!

### CODE REVIEW

**Comment by NathanKell** [comment]
@rbray89  Maaaaan you're fast :P

**Comment by rbray89** [comment]
Haha, just email :) That being said... I'm not sure this will actually effect anything, but it is good reference for the future.

**Comment by NathanKell** [comment]
Fair enough. Blacks was looking through the source, and is going to see if there are any other hard references to Kerbin. They also mention, however, that the Tracking Station scene is working perfectly, so whatever you're doing there works fine in Kopernicus/RSS :)

**Comment by rbray89** [comment]
Is that in EVE Overhaul or 7.4? I recently moved to the CB lookup rather than transform lookup in EVE Overhaul, and went with the frame delay for loading to try and fetch the correct names.

**Comment by NathanKell** [comment]
Overhaul, Blacks is testing RVE.

**Comment by rbray89** [comment]
Ah, perfect. Is there anything specifically broken then?

**Comment by NathanKell** [comment]
Blacks is going to be making an issue covering all that, I believe.

**Comment by Blacksuu** [comment]
Hello
I am messing / testing with RVE from some time testing how it work release in combo RSS + RVE + Pingopete work try to help make EVE compatible with RSS / Kopernicus, i post some feedback on forum to but with nick Blacks (on github nick was take)

At this moment base on test my target was to track 2 thing:
1. if is any place were it was set Kerbin name
2. were & how it define loading / query trigger moment in your code to find reason way Eve it require to do some manually force loading texture each time is open game once in a specific GameScenes what in your code are 4 stage  A. GameScenes.MAINMENU, B. GameScenes.FLIGHT, C. GameScenes.SPACECENTER, D. GameScenes.TRACKSTATION (if there are more then i not find yet :D)

A. GameScenes.MAINMENU it require load CityLights to fix partial white continent
B. GameScenes.FLIGHT it require to load Atmosphere with each layer what was make in config & if it go out in map mode (alt +m) it need to load terrain section
C. GameScenes.SPACECENTER if step A & B are done all is fine just terrain it sometime grumpy aka ocean fail to be load corect
D. GameScenes.TRACKSTATION is single place what it not require to be done nothing all working perfect with out need to be done anything, that in case if something serious it happen what usual is seen in debug instant from a lot spam exception

searching about how loading / query mechanism work is not easy coz code is spread in all your file having specific condition to be use / trigger base on principle with if & then algorithm (p.s. i am noob in coding but i have basic / rudimentary eye to read a code), for example i see in AtmospherePQS.cs you describe / set ruls when & how to be load things, but base on my test it seams to work perfectly only GameScenes.TRACKSTATION see code line 99 from were it start basically all condition what you define. I was try to speak with Nathan to see if is something wrong but both was overwhelm coz we not know exactly how is design all your code

https://github.com/rbray89/EnvironmentalVisualEnhancements/blob/Overhaul/Clouds/AtmospherePQS.cs

soo if it can be found were & how is can be fix, improve code, to fix what i describe early all it will be fine between EVE & Kopernicus/RSS

about dx11, opengl issue i think you know there are problem but that part is to much for me, same hope game log what i sent you on forum mail to help, i will be around keep digging to spot some issue but some hint it will be good :)
P.S. Do not change code about how it work GameScenes.TRACKSTATION !!!! try to use like guide to make rest work if is possible but i for sure u know much better :)

**Comment by rbray89** [comment]
You guys have an easy setup I could borrow to get RO working to test these issues?

**Comment by NathanKell** [comment]
Sure, although RO really isn't needed per se, all you need is RSS (+kopernicus), the RSS textures, and pete's RVE github repo

**Comment by NathanKell** [comment]
Updated comment with links

**Comment by Blacksuu** [comment]
don't use at this point Pete file coz he was mest up with RSSKopernicus file, plus he was use old version use texture what u have on default but replace only Kerbin with Earth & you are set

**Comment by NathanKell** [comment]
You'd also want hyperedit, I assume, and if you want an easy way to launch craft, use this: https://github.com/KSP-RO/RealismOverhaul/blob/master/ROMini.cfg instead of a full RO install.

**Comment by NathanKell** [comment]
Makes sense. Best to get it working with "pure" EVE first anyway.

**Comment by Blacksuu** [comment]
exactly what texture are use, how many layer not mater default eve texture is good inaff but with condition to be replace 1 name kerbin with earth :) aka first step for make all moder happy who use kopernicus system

**Comment by rbray89** [comment]
Sooo... I took a look at Black's logs... It seems there is more than 1 CB with the names you are looking up. Any thoughts on this? Apparently sometimes I use "First()" and other times I use "Single()"

**Comment by NathanKell** [comment]
@rbray89  That...seems odd. You're grabbing them from FlightGlobals.Bodies, yeah? Or are you doing Resources.FindAll?

(Also: LINQ and foreach are bad for realtime applications in Unity, FYI, they're rather slower than for and can leak)

**Comment by NathanKell** [comment]
(i.e. they're ok in Awake/Start/etc but not (fixed)update or OnGUI)

**Comment by rbray89** [comment]
CelestialBody[] celestialBodies = CelestialBody.FindObjectsOfType(typeof(CelestialBody)) as CelestialBody[];
            return celestialBodies.Single(n => n.bodyName == body);

**Comment by rbray89** [comment]
Yeah, I only do lookups for setup purposes :)

**Pull request merged**
